"""extend users with subscription geo consent

Revision ID: 4673ecf5260c
Revises: 48f594ababa3
Create Date: 2026-05-18 18:10:43.548842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4673ecf5260c'
down_revision: Union[str, None] = '48f594ababa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('subscription_tier', sa.String(length=16), server_default='free', nullable=False))
    op.add_column('users', sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('allow_location_metadata', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('last_ip', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('last_geo_country', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('last_geo_region', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('last_geo_city', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('last_geo_lat', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('last_geo_lng', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('last_geo_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_geo_at')
    op.drop_column('users', 'last_geo_lng')
    op.drop_column('users', 'last_geo_lat')
    op.drop_column('users', 'last_geo_city')
    op.drop_column('users', 'last_geo_region')
    op.drop_column('users', 'last_geo_country')
    op.drop_column('users', 'last_ip')
    op.drop_column('users', 'allow_location_metadata')
    op.drop_column('users', 'subscription_expires_at')
    op.drop_column('users', 'subscription_tier')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
