"""add admin_audit table

Revision ID: 89d4a8267d23
Revises: 43a1bec11fce
Create Date: 2026-05-18 14:24:49.163006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '89d4a8267d23'
down_revision: Union[str, None] = '43a1bec11fce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('admin_email', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('target_email', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_action'), 'admin_audit', ['action'], unique=False)
    op.create_index(op.f('ix_admin_audit_admin_email'), 'admin_audit', ['admin_email'], unique=False)
    op.create_index(op.f('ix_admin_audit_admin_id'), 'admin_audit', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_created_at'), 'admin_audit', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_audit_target_user_id'), 'admin_audit', ['target_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_audit_target_user_id'), table_name='admin_audit')
    op.drop_index(op.f('ix_admin_audit_created_at'), table_name='admin_audit')
    op.drop_index(op.f('ix_admin_audit_admin_id'), table_name='admin_audit')
    op.drop_index(op.f('ix_admin_audit_admin_email'), table_name='admin_audit')
    op.drop_index(op.f('ix_admin_audit_action'), table_name='admin_audit')
    op.drop_table('admin_audit')
    # ### end Alembic commands ###
