"""add toss billing key columns

Revision ID: f2a0d7acdf14
Revises: a8452d63690e
Create Date: 2026-05-18 20:07:29.707357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f2a0d7acdf14'
down_revision: Union[str, None] = 'a8452d63690e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('toss_customer_key', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('toss_billing_key', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('toss_card_brand', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('toss_card_last4', sa.String(length=8), nullable=True))
    op.add_column('users', sa.Column('toss_billing_issued_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_billing_error', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_toss_customer_key'), 'users', ['toss_customer_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_toss_customer_key'), table_name='users')
    op.drop_column('users', 'last_billing_error')
    op.drop_column('users', 'toss_billing_issued_at')
    op.drop_column('users', 'toss_card_last4')
    op.drop_column('users', 'toss_card_brand')
    op.drop_column('users', 'toss_billing_key')
    op.drop_column('users', 'toss_customer_key')
    # ### end Alembic commands ###
